export const CHORD_QUEUE_ADD = 'CHORD_QUEUE_ADD';
export const CHORD_QUEUE_REMOVE = 'CHORD_QUEUE_REMOVE';
export const NOTES_SET_EVENTS = 'NOTES_SET_EVENTS';
export const NOTES_SET_MODE = 'NOTES_SET_MODE';
export const NOTES_SET_CURRENT_TIME = 'NOTES_SET_CURRENT_TIME';
export const NOTES_SET_CURRENT_EVENTS = 'NOTES_SET_CURRENT_EVENTS';
export const NOTES_SET_DEFAULTS = 'NOTES_SET_DEFAULTS';
